export const categoryList = [
    {
      id: 1,
      value: 'place',
      label: ' Laptop',
    },
    {
      id: 2,
      value: 'dish',
      label: 'Mobile',
    },
  ];
  
  
  
  export const dataList = [
    {
      id: 1,
      title: 'lenevo',
      serviceTime: '500',
      deliveryFee: 2000,
      category: 'place',
      cuisine: 'laptop',
      rating: 5,
      price: 1000,
      coverSrc: '/images/Laptop/image7.jpg',
    },
    {
      id: 2,
      title: 'Dell',
      serviceTime: '1000',
      deliveryFee: 1500,
      category: 'place',
      cuisine: 'laptop',
      rating: 4,
      price: 1400,
      coverSrc: '/images/Laptop/image8.jpeg',
    },
    {
      id: 3,
      title: 'ASUS',
      serviceTime: '1200',
      deliveryFee: 1560,
      category: 'place',
      cuisine: 'laptop',
      rating: 3,
      price: 1200,
      coverSrc: '/images/Laptop/image9.jpg',
    },
    {
      id: 4,
      title: 'HP',
      serviceTime: '1090',
      deliveryFee: 2560,
      category: 'place',
      cuisine: 'laptop',
      rating: 1,
      price: 1800,
      coverSrc: '/images/Laptop/image10.jpg',
    },
    {
      id: 5,
      title: 'Samsung',
      serviceTime: '3000',
      deliveryFee: 3560,
      category: 'place',
      cuisine: 'laptop',
      rating: 5,
      price: 2000,
      coverSrc: '/images/Laptop/image11.jpeg',
    },
    {
      id: 6,
      title: 'DELL',
      serviceTime: '1500',
      deliveryFee: 3332,
      category: 'place',
      cuisine: 'laptop',
      rating: 5,
      price: 3000,
      coverSrc: '/images/Laptop/image12.jpg',
    },
    {
      id: 7,
      title: 'One Plus 10',
      serviceTime: '7500',
      deliveryFee: 3000,
      category: 'dish',
      cuisine: 'mobile',
      rating: 2,
      price: 2200,
      coverSrc: '/images/Mobile/image1.jpeg',
    },
    {
      id: 8,
      title: 'Redmi Note 9',
      serviceTime: '2000',
      deliveryFee: 1200,
      category: 'dish',
      cuisine: 'mobile',
      rating: 1,
      price: 1900,
      coverSrc: '/images/Mobile/image2.jpeg',
    },
    {
      id: 9,
      title: 'Iphone7',
      serviceTime: '2400',
      deliveryFee: 2500,
      category: 'dish',
      cuisine: 'mobile',
      rating: 4,
      price: 2750,
      coverSrc: '/images/Mobile/image3.jpg',
    },
    {
      id: 10,
      title: 'Samsung Galexy',
      serviceTime: '1700',
      deliveryFee: 1900,
      category: 'dish',
      cuisine: 'mobile',
      rating: 2,
      price: 1350,
      coverSrc: '/images/Mobile/image4.jpg',
    },
    {
      id: 11,
      title: 'Motorola',
      serviceTime: '2000',
      deliveryFee: 3500,
      category: 'dish',
      cuisine: 'mobile',
      rating: 3,
      price: 3300,
      coverSrc: '/images/Mobile/image5.jpg',
    },
    {
      id: 12,
      title: 'Samsung',
      serviceTime: '9000',
      deliveryFee: 4500,
      category: 'dish',
      cuisine: 'mobile',
      rating: 2,
      price: 3100,
      coverSrc: '/images/Mobile/image6.jpg',
    },
  ];